### ISSUE TITLE
What's going on in the USB camera code?

### ISSUE THREAD

**Issue by erikuhlmann** [wpilibsuite/SmartDashboard#10]
Specifically, this: https://github.com/wpilibsuite/SmartDashboard/blob/master/smartdashboard/src/edu/wpi/first/smartdashboard/gui/elements/WebcamViewerExtension.java#L185-L207

The comments aren't really helpful, and I'm curious as to what it does considering that I've recently [blindly ported it to node.js](https://github.com/erikuhlmann/SmartDashboard.js/blob/master/default-widgets.js#L1102) without actually understanding what it is

It seems to try to detect if it needs to copy in this huffman table and copies it in - why? Does `imaqFlatten` not create valid JPEGs?

**Comment by SamCarlberg** [comment]
@ThomasJClark

**Comment by ThomasJClark** [comment]
> It seems to try to detect if it needs to copy in this huffman table and copies it in - why? Does imaqFlatten not create valid JPEGs?

For your use-case (streaming to the browser) you can probably skip that step

MJPEG encoders don't include the Huffman table on every frame, since it's almost always the same so it would be redundant.  Java's `ImageIO` stuff is designed for decoding individual JPEGs, so it has trouble decoding a single frame from an MJPEG.  That code fixes this by inserting the raw bytes of a "standard" Huffman table into the byte stream.  

The section of code you linked to was copied from [this post on Chief Delphi](https://www.chiefdelphi.com/forums/showthread.php?t=134404), which was adapted from [this python script](http://www.mail-archive.com/linux-uvc-devel@lists.berlios.de/msg02255/mjpeg2jpeg.py).  Java might actually have some way to explicitly set a default table, which would definitely be more readable and efficient, but it was the last week of build season and people were angry so we merged it.
