### ISSUE TITLE
Sendable chooser values changes when robot starts

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/SmartDashboard#2]
Many teams experienced an issue with the SendableChooser widget in the SmartDashboard and robot code that caused the selected auto mode to not be the one that is run. The issue is that SmartDashboard would come up with the saved layout including the SendableChooser. The team would select the desired auto mode. Then the robot comes up, with the actual SendableChooser object that sets the selection to the default value. The team dashboard selection is then overwritten in NetworkTables.

A possible solution to this is to make the dashboard selections stick. That is when it notices the change from robot that is different than it's displayed UI, just set it back again. This makes sense to me since the sendable chooser UI element is supposed to represent the value returned when the robot grabs it.

**Comment by ThadHouse** [comment]
Looking through this issue and https://github.com/wpilibsuite/allwpilib/issues/206, this is actually caused by SmartDashboard not updating the selected value when a server is connected. The robot side code does not actually send a selected value, so the robot just ends up using the default value. We are planning on adding a connection listener to SmartDashboard where upon server connection the selected value will actually be sent.
